# Generated by Django 4.1.7 on 2023-04-05 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_propertyvaloration_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupreservation',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='groupReservationAssigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
