# Generated by Django 4.1.7 on 2023-04-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_groupreservation_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestservice',
            name='direction',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='interestservice',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='interestservice',
            name='type',
            field=models.CharField(choices=[('Salud', 'Health'), ('Alimentación', 'Feeding'), ('Deporte', 'Sport'), ('Entretenimiento', 'Entertainment'), ('Transporte', 'Transport'), ('Educación', 'Education')], default='-', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='experience',
            unique_together={('place', 'student')},
        ),
    ]
