# Generated by Django 4.1.7 on 2023-04-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_alter_interestservice_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestserviceproperty',
            name='distance',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='interestserviceproperty',
            unique_together={('distance', 'busTime', 'carTime', 'walkTime', 'interestService', 'property')},
        ),
    ]
