# Generated by Django 4.1.7 on 2023-04-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_alter_interestserviceproperty_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentannouncement',
            name='photo',
            field=models.ImageField(null=True, upload_to='studentsAnnouncement/'),
        ),
    ]
